### ISSUE TITLE
V1.2.1版本的docker-compose.yml中bisheng前后端镜像版本为啥不改？

### ISSUE THREAD

**Issue by doAIs** [dataelement/bisheng#1335]
```
  backend:
    container_name: bisheng-backend
    image: dataelement/bisheng-backend:v1.2.0

  frontend:
    container_name: bisheng-frontend
    image: dataelement/bisheng-frontend:v1.2.0
```

不应该修改成v1.2.1吗？
