### ISSUE TITLE
向量数据库 Milvus 如何应用到项目中

### ISSUE THREAD

**Issue by huangbaichao** [dataelement/bisheng#32]
使用源码私有化部署运行后端backend，并且向量数据库使用仓库默认的配置
```
vectorstores:
    # Milvus 最低要求cpu 4C 8G 推荐4C 16G
    Milvus: # 如果需要切换其他vectordb，确保其他服务已经启动，然后配置对应参数
      connection_args: { "host": "110.16.193.170", "port": "50032", "user": "", "password": "", "secure": False }
```
本机有使用docker部署Milvus，但后端项目未使用其配置。

现进行文档问答配置的时候，Milvus组件连接向量数据库失败，连接的地址是：192.168.106.116:19530
这个地址是在哪里配置的，对应逻辑是哪里调用的，应该如何修改使其正常运行？

![image](https://github.com/dataelement/bisheng/assets/9191067/06d76fbd-0f62-4519-a7ce-294732278b90)
