### ISSUE TITLE
请问本地部署接入openai接口创建本地知识库，为何回答没有参考来源？

### ISSUE THREAD

**Issue by 1347027216** [dataelement/bisheng#333]
> 这是我的基础配置，服务均测试过已成功启动，以下服务使用docker容器部署，开发环境为windows conda 

```yaml

knowledges:
  unstructured_api_url: ""  # 毕昇非结构化数据解析服务地址，提供包括OCR文字识别、表格识别、版式分析等能力。非必填，溯源必填
  embeddings: # 配置知识库的embedding服务，以下示例填写了两类embedding服务的配置方法，第一个是openai的embedding模型服务的配置方法，第二个是本地部署的embedding模型服务的配置方法，如果有多个可以添加多个
    text-embedding-ada-002: # 知识库下拉框中显示的embedding模型的名称，可自定义
      openai_api_base: "https://api.openai.com/v1"
      openai_proxy: "" # 如果是自己代理的服务地址，则填在这里
      openai_api_key: "我的key" # 私有的，openai账号的key
      # deployment: ""  # azure 部署需要
      # openai_api_type: ""    # azure api_type
      # openai_api_version: ""  # azure api_version
    embedding-host: # 知识库下拉框中显示的embedding模型的名称，可自定义
      host_base_url: "" # 在模型管理页面中已上线的embedding服务的地址
    model: "" # 在模型管理页面中已上线的embedding模型的名称
  vectorstores:
    # Milvus 最低要求cpu 4C 8G 推荐4C 16G
    Milvus: # 如果需要切换其他vectordb，确保其他服务已经启动，然后配置对应参数
      connection_args: { 'host': '127.0.0.1', 'port': '19530', 'user': '', 'password': '', 'secure': False }
      # partiton-key model, 用于分区的字段，如果不配置默认True， 分区后，新的partiton不会新建collection，可以通过增加suffix强制增加collection
      is_partition: False
      partition_suffix: 1
    # 可选配置，有些类型的场景使用ES可以提高召回效果
    ElasticKeywordsSearch:
      elasticsearch_url: 'http://127.0.0.1:9200'
      ssl_verify: "{'basic_auth': ('elastic', 'password')}"
  minio: # 如果要支持溯源功能，由于溯源会展示源文件，必须配置 oss 存储
    SCHEMA: false         # 是否支持 https
    CERT_CHECK: false         # 是否校验 http证书
    MINIO_ENDPOINT: "127.0.0.1:59100"       # 这个地址用来写请求
    MINIO_SHAREPOIN: "127.0.0.1:59100"      # 为保证外网和内网隔离。 浏览器获取连接是这个域名
    MINIO_ACCESS_KEY: "minioadmin"
    MINIO_SECRET_KEY: "minioadmin"
```

知识库问答的时候无"参考来源"，在官网的Demo中试用正常，请问是我的配置有问题吗
![微信截图_20240205174001](https://github.com/dataelement/bisheng/assets/58221113/31972783-66be-4142-9511-10cb01cbcfc7)

- **另外这个地方似乎是一个bug，在windows上传文件的时候会出现路径解析失败**
- `\api\v1\knowledge.py : 125行 `
```python
    for path in file_path:
        filepath, file_name = file_download(path)
        md5_ = filepath.rsplit('/', 1)[1].split('.')[0].split('_')[0]
        # 是否包含重复文件
        repeat = session.exec(
            select(KnowledgeFile).where(KnowledgeFile.md5 == md5_, KnowledgeFile.status == 2,
                                        KnowledgeFile.knowledge_id == knowledge_id)).all()
        status = 3 if repeat else 1
        remark = 'file repeat' if repeat else ''
        db_file = KnowledgeFile(knowledge_id=knowledge_id,
                                file_name=file_name,
                                status=status,
                                md5=md5_,
                                remark=remark,
                                user_id=payload.get('user_id'))
```
- 我的解决方案：
```python
import platform

# other code

if platform.system().upper() == "WINDOWS":
    md5_ = filepath.rsplit('\\', 1)[1].split('.')[0]
else:
    md5_ = filepath.rsplit('/', 1)[1].split('.')[0].split('_')[0]
```
